### ISSUE TITLE
dificultades para exportar archivo firmado.

### ISSUE THREAD

**Issue by JuanJoseDev88** [gdiazs/MITyCLib#4]
Hola, de nuevo yo.Tengo inconvenientes para exportar el archivo firmado a una carpeta, cuando termina de ejecutar el programa el archivo se genera en el mismo directorio del proyecto pero al tratar de cambiar la ruta no pasa nada. La modificación la hago en la clase GenericXMLSignature  en la siguiente linea:

public final static String OUTPUT_DIRECTORY = "."; 

la cual modifico por 

public final static String OUTPUT_DIRECTORY = "/home/jperez/Documentos/xml";

pero no me funciona. haciendo debug en esa clase me encontré con la siguientes lineas de codigo

```
// Firmamos el documento
        Document docSigned = null;
        try {
            Object[] res = firma.signFile(certificate, dataToSign, privateKey, provider);
            docSigned = (Document) res[0];
        } catch (Exception ex) {
            System.err.println("Error realizando la firma");
            ex.printStackTrace();
            return;
        }

        // Guardamos la firma a un fichero en el home del usuario
        String filePath = OUTPUT_DIRECTORY + File.separatorChar + getSignatureFileName();
        System.out.println("Firma salvada en en: " + filePath);
        saveDocumentToFile(docSigned, getSignatureFileName());
    }
```
y observo que el valor de la variable docSigned permanece siempre en null, ¿es esto normal? ¿de que forma puedo modificar exitosamente la ruta de exportación de mi archivo firmado?

**Comment by maparamo** [comment]
Buen dia, Juan. He luchado con firmar documentos XML usando PHP pero ha sido imposible, no se si podrias ayudarme a guiar como usar MITyCLibXAdES para hacerlo, vi que ya lo lograste.

Mil gracias

**Comment by JuanJoseDev88** [comment]
@maparamo Al principio pude hacerla funcionar pero luego removieron algo del git, no estoy seguro que, y cuando volvi a importar la librería no me funcionaba. Finalmente desistí de usarla y empecé nuevamente con Xades4j. Con PHP no podría ayudarte porque trabajo con Java.

**Comment by gdiazs** [comment]
Hola, sucede que el pom.xml hacía referencia a un repositorio maven personal que había yo montando en la cloud de REDHAT pero las politicas cambiaron y me borraron el servidor, entonces hice el cambio para hacer referencia a un repositorio maven que es publico pero que desconozco su disponibilidad en el futuro.

El url del repo maven es: http://maven.petalslink.com/repo
Y se configura en: https://github.com/gdiazs/MITyCLib/blob/master/pom.xml

El proyecto está en un claro abandono por parte de españa y me lo traje aquí porque hay personas que aún lo usan y el codigo fuente ya no está en otro lado 

Saludos
