### ISSUE TITLE
Migrate documentation

### ISSUE THREAD

**Issue by gdiazs** [gdiazs/MITyCLib#7]
Migrate documentation to readme format [from here](https://web.archive.org/web/20151108060654/http://oficinavirtual.mityc.es:80/componentes/mityclibxades/index.html)

**Comment by fochoac** [comment]
Hola Guillermo, cuentame que es lo que necesitas exactamente.
Quieres que se copie la documentacion del sitio web o que se genere la documentacion.

Comentame por favor para colaborar en este proyecto.

Saludos

**Comment by gdiazs** [comment]
Hola Vinicio, hasta ahora veo el mensaje. En esta página: 
 https://web.archive.org/web/20151108060654/http://oficinavirtual.mityc.es:80/componentes/mityclibxades/index.html 
se encuentra un resplado de lo que alguna vez fue la documentación original de estas librerias. 

Todo el repositorio de este proyecto original mente desparació, por lo que lo considero a este como una especie de Fork de consulta para aquellos que de alguna u otra forma aún utilizan las librerias. 

La idea es copiar y pegar esa documentación pero darle un poco de formato al estilo README.md.

**Comment by fochoac** [comment]
Hola Guillermo, sabes que pase lo que pienso es importane de la documentación.
No puedo remplazar todos los links dado que se apunta al JavaDoc y a pruebas unitarias en si y no se si esa información se encuentra disponible en el repositorio.
Por favor ayudame revisando el wiki del fork que realice [https://github.com/fochoac/MITyCLib/wiki](https://github.com/fochoac/MITyCLib/wiki)

Me comentas si es suficiente con eso o falta algo mas.

Saludos

**Comment by gdiazs** [comment]
Gracias, no te preocupes. Gracias por el aporte. 
Vi la wiki y te quedó muy bien. 

Si de algo sirve estos son los ejemplos: https://github.com/gdiazs/MITyCLib/tree/master/MITyCLibXADES/src/test/java/es/mityc/javasign/xades/examples/signformats

Y el javadoc bien se puede cambiar por las clases en sí.

**Comment by fochoac** [comment]
Estimado Guillermo,

Se genero la documentación completa del proyecto:
Para que tengas toda la documentación hay que realizar los siguientes pasos:

1. Hay que fusionar el pull request #8 
1. Hay que configurar el proyecto para que soporte paginas web estáticas como se muestra en la imagen adjunta.

![image](https://user-images.githubusercontent.com/3372356/97822873-3c21ac80-1c85-11eb-84f2-7ceeb2cd6c3c.png)

Hay que validar que el javadoc este funcionado. La ruta deberia ser: [JAVADOC](https://gdiazs.github.io/MITyCLib/)

**Wiki**
Dado que no puedo realizar ningún commit directamente sobre el branch de la wiki, por favor realiza lo siguiente:

1. Clona la url [wiki gdiazs](https://github.com/gdiazs/MITyCLib.wiki.git)
1. Remplaza todos los documentos de tu branch por lo arjuntos en el archivo zip, [MITyCLib.wiki.zip](https://github.com/gdiazs/MITyCLib/files/5472392/MITyCLib.wiki.zip)

Finalizado todo esto se deberia de probar que las referencias esten correctas hacia tu sitio web para el JavaDoc desde las paginas de la wiki.

Creo que con esto se terminaria la documentación.

Cualquier novedad me comentas,

Saludos,
Vinicio
